export const CARD_ITEMS = [
  {
    title: 'Amsterdam Lights',
    url: 'https://bonifique.life/media/photo-1558551649-e44c8f992010.jpg',
    link: './Amsterdam',
    // label: 'Amsterdam Lights',
    price: 500,
  },
  {
    title: 'Art & Fashion Photography: Morocco',
    url: 'https://bonifique.life/media/14.05_%D0%BE%D0%B1%D0%B5%D1%80%D0%BE%D0%B8.jpg',
    link: './Morocco',
    // label: 'Art & Fashion Photography: Morocco',
    price: 600,
  },
  {
    title: 'Charm of Bavaria',
    url: 'https://bonifique.life/media/pexels-photo-2832061.jpg',
    link: './Bavaria',
    // label: 'Charm of Bavaria',
    price: 700,
  },
  {
    title: 'Cozy Zakopane',
    url: 'https://bonifique.life/media/91054883_25889433547.jpg',
    link: './Zakopane',
    // label: 'Cozy Zakopane',
    price: 800,
  },
  {
    title: 'Dia de los Muertos: Mexico',
    url: 'https://bonifique.life/media/%D0%A1%D0%BD%D0%B8%D0%BC%D0%BE%D0%BA_%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%B0_2021-08-28_%D0%B2_22.21.53_oa6wYrb.png',
    link: './Mexico',
    // label: 'Dia de los Muertos: Mexico',
    price: 900,
  },
  {
    title: 'Ecology of Stockholm',
    url: 'https://bonifique.life/media/pexels-photo-4032444.jpg',
    link: './Stockholm',
    // label: 'Ecology of Stockholm',
    price: 1000,
  },
  {
    title: 'Fairy Karelia',
    url: 'https://bonifique.life/media/1519196252_vodopady-zimoy.jpg',
    link: './Karelia',
    // label: 'Fairy Karelia',
    price: 1500,
  },
  {
    title: 'Fairytale Andalusia',
    url: 'https://bonifique.life/media/Hotel_Alfonso_XIII_a.jpg',
    link: './Andalusia',
    // label: 'Fairytale Andalusia',
    price: 2000,
  },
  {
    title: 'Kenya: the Great Animals Migration',
    url: 'https://bonifique.life/media/photo-1577971132997-c10be9372519.webp',
    link: './Kenya',
    // label: 'Kenya: the Great Animals Migration',
    price: 3000,
  },
  {
    title: 'Land of ice and volcanoes',
    url: 'https://bonifique.life/media/103391299_6200804686.jpg',
    link: './Iceland',
    // label: 'Land of ice and volcanoes',
    price: 4000,
  },
];
