export const PARAMETER_ITEMS = [
  {
    name: 'price',
    label: 'Price',
    displayType: '',
    max: 4200,
    min: 1,
    isActive: false,
    type: 'range',
  },
  {
    name: 'Budget',
    displayType: '',
    max: 17820,
    min: 1,
    isActive: false,
    type: 'range',
  },
  {
    name: 'Travel format',
    displayType: '',
    choices: ['Individual', 'Group', 'Guidebooks'],
    isActive: false,
    type: 'checkbox',
  },
  {
    name: 'Accommodation style',
    displayType: '',
    choices: ['Modern', 'Cosiness', 'Loft', 'Classic', 'Luxury'],
    isActive: false,
    type: 'checkbox',
  },
  {
    name: 'Type of travel',
    displayType: '',
    choices: [
      'Expedition',
      'Hunting and fishing',
      'Ecotourism',
      'Wildlife',
      'Family holiday',
      'Beach vacation',
      'With children',
      'For children',
      'Gastronomic and tasting',
      'SPA',
      'Medical',
      'Volunteer programs',
      'Educational',
      'Movie plots',
      'Travel by train',
      'Sporting events',
      'Music events',
      'Yoga',
      'Extreme',
      'Winter sport',
      'Wedding',
      'Romantic',
      'Sea cruises',
      'Christmas and New Year',
      'Art of photography',
      'Exhibitions',
      'Festivals and parades',
      'Cinema adventure',
    ],
    isActive: false,
    type: 'checkbox',
  },
  {
    name: 'Taste',
    displayType: '',
    choices: [
      'European',
      'Asian',
      'Italian',
      'Spanish',
      'Vegetarian',
      'American',
      'Hearty',
      'Light',
      'Mexican',
    ],
    isActive: false,
    type: 'checkbox',
  },
  {
    name: 'Locations',
    displayType: '',
    choices: [
      'Europe',
      'Asia',
      'Africa',
      'America',
      'Australia and Oceania',
      'Antarctic',
      'Around the world',
      'Russia',
    ],
    isActive: false,
    type: 'checkbox',
  },
  {
    name: 'Season',
    displayType: '',
    choices: ['Winter', 'Spring', 'Summer', 'Autumn'],
    isActive: false,
    type: 'checkbox',
  },
  {
    name: 'Category',
    displayType: '',
    choices: ['Unique economy', 'Magnifique premium', 'Bonifique business'],
    isActive: false,
    type: 'checkbox',
  },
  {
    name: 'Number of travellers',
    displayType: '',
    max: 10,
    min: 1,
    isActive: false,
    type: 'range',
  },
  {
    name: 'Duration, days',
    displayType: '',
    max: 14,
    min: 1,
    isActive: false,
    type: 'range',
  },
];
